const express = require('express');
const cors = require('cors');
const db = require('./db');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware configuration layer
app.use(cors());          // Allows your React frontend port to communicate securely
app.use(express.json());  // Allows your API routes to parse incoming JSON request payloads

// ==========================================
// 1. AUTHENTICATION & LOGIN MANAGEMENT
// ==========================================
app.post('/api/auth/login', async (req, res) => {
    try {
        const { email, password } = req.body;

        // Matches exact schema properties: school_email, password_hash, full_name, role
        const result = await db.query(
            'SELECT id, full_name, school_email, role, student_id FROM users WHERE school_email = \$1 AND password_hash = \$2;',
            [email, password]
        );

        if (result.rows.length === 0) {
            return res.status(401).json({ success: false, message: 'Invalid institutional email or password.' });
        }

        const user = result.rows[0]; // Gets the first user row record object directly
        res.json({
            success: true,
            user: {
                id: user.id,
                name: user.full_name,
                email: user.school_email,
                role: user.role.toLowerCase(), // Converts 'Student' / 'Organizer' string values cleanly to lowercase
                studentId: user.student_id
            }
        });
    } catch (err) {
        console.error('Auth Error:', err.message);
        res.status(500).send('Server error processing authentication request');
    }
});

// ==========================================
// 2. CAMPUS EVENTS CONTROLLERS
// ==========================================

// GET: Fetch all active events utilizing the view generated by your SQL script
app.get('/api/events', async (req, res) => {
    try {
        const result = await db.query('SELECT * FROM event_list_view;');
        res.json(result.rows);
    } catch (err) {
        console.error('Fetch Events Error:', err.message);
        res.status(500).send('Server Error fetching comprehensive event records');
    }
});

// GET: Query a singular specific event by its ID structure
app.get('/api/events/:id', async (req, res) => {
    try {
        const { id } = req.params;
        const result = await db.query('SELECT * FROM event_list_view WHERE event_id = \$1;', [id]);
        
        if (result.rows.length === 0) {
            return res.status(404).send('Event record not found in system schema');
        }
        res.json(result.rows[0]); // Returns only the single object row to the frontend view handler
    } catch (err) {
        console.error('Single Event Fetch Error:', err.message);
        res.status(500).send('Server Error fetching targeted event details');
    }
});

// POST: Add a completely new event entry into the database fields (For CreateEvent.jsx)
app.post('/api/events', async (req, res) => {
    try {
        const { event_name, description, venue, event_date, start_time, end_time, organizer_id, department_id } = req.body;
        const result = await db.query(
            `INSERT INTO events (event_name, description, venue, event_date, start_time, end_time, organizer_id, department_id, status) 
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'Upcoming') RETURNING *;`,
            [event_name, description, venue, event_date, start_time, end_time, organizer_id, department_id]
        );
        res.status(201).json(result.rows);
    } catch (err) {
        console.error('Create Event Error:', err.message);
        res.status(500).send('Server Error creating a new event entry profile');
    }
});

// ==========================================
// 3. STUDENT REGISTRATION & ATTENDANCE LOGS
// ==========================================

// POST: Process incoming student registration requests (For Register.jsx)
app.post('/api/registrations', async (req, res) => {
    try {
        const { student_id, event_id } = req.body;
        
        // Inserts rows using your database schema logic constraints
        const result = await db.query(
            `INSERT INTO registrations (student_id, event_id, registration_date, attendance_status) 
             VALUES ($1, $2, NOW(), 'Absent') RETURNING *;`,
            [student_id, event_id]
        );
        res.status(201).json({ success: true, registration: result.rows[0] });
    } catch (err) {
        console.error('Registration Insertion Error:', err.message);
        res.status(500).send('Server Error processing student registration payload');
    }
});

// GET: Fetch master registration ledger rows from your custom database view (For MyEvents / RegisteredStudents)
app.get('/api/attendance', async (req, res) => {
    try {
        const result = await db.query('SELECT * FROM event_attendance_view;');
        res.json(result.rows);
    } catch (err) {
        console.error('Attendance Log Fetch Error:', err.message);
        res.status(500).send('Server Error pulling registration attendance view fields');
    }
});

// POST: Manage QR verification requests to register student attendance (For QRScanner.jsx)
app.post('/api/attendance/scan', async (req, res) => {
    try {
        const { qr_token_string } = req.body; // Evaluates parsed ticket token string emitted by web camera hook
        const result = await db.query(
            `UPDATE registrations 
             SET attendance_status = 'Attended' 
             WHERE qr_token = $1 RETURNING *;`,
            [qr_token_string]
        );
        
        if (result.rows.length === 0) {
            return res.status(404).json({ success: false, message: 'Invalid or unregistered digital ticket token.' });
        }
        res.json({ success: true, message: 'Attendance confirmed and tracked!', record: result.rows[0] });
    } catch (err) {
        console.error('QR Scan Processing Error:', err.message);
        res.status(500).send('Server Error checking scan validation tokens');
    }
});

// ==========================================
// 4. BOOTSTRAP ACTIVATION HANDSHAKE
// ==========================================
app.listen(PORT, () => {
    console.log(`🚀 Unified API Engine running dynamically on port ${PORT}`);
});
